### ISSUE TITLE
Please add support for `pattern` properties

### ISSUE THREAD

**Issue by ex-nerd** [kevinrenskers/raml2html#119]
Given the following sample code:

```
traits:
  - secured:
      queryParameters:
        MyAuthParam:
          type: string
          pattern: ^[a-zA-Z].+$
      headers:
        MyAuthHeader:
          pattern: ^[0-9a-z].+$
```

I would expect to see something like `api-designer` generates, e.g.:

* **MyAuthParam** _string matching ^[a-zA-Z].+$_
* **MyAuthHeader** _string matching ^[0-9a-z].+$_
